### PR TITLE
Report the versions of dependencies.

### PR DESCRIPTION
**Pull request by bbeck**
This change updates the VersionServlet to no longer just report the version of the
main application artifact but also of all dependencies found in the classpath.
Dependencies are discovered by scanning the classpath and looking for
`pom.properties` files in `META-INF/maven` subdirectories.  These `pom.properties`
files are put into jars when Maven builds packages and includes the version of the
dependency making it ideal for this use case.

### CODE REVIEW

**Comment by nbauernfeind** [comment]
I think it might make more sense to use a resource class instead of a servlet.

It would be nice to filter on artifactId and/or groupId. Using a resource would make the implementation simpler.

I don't think you want to create your own ObjectMapper. You should pass it in from the environment. Otherwise you won't respect modifications like snake case, or many other common features people use from jackson.

**Comment by bbeck** [comment]
The admin port doesn't seem to have Jersey wired up to it, so the only thing you can add are servlets.

Filtering on artifactId and/or groupId might be nice, but the implementation is Maven agnostic, so if there were some other version mechanism those concepts wouldn't necessarily make sense.

Updated for the object mapper changes.

**Comment by nbauernfeind** [comment]
Looks great to me =).

**Comment by bbeck** [comment]
FYI for any lurkers output now looks like:

``` json
{
    "application": "0.0.1-SNAPSHOT",
    "dependencies": {
        "ch.qos.logback:logback-classic": "1.1.2",
        "ch.qos.logback:logback-core": "1.1.2",
        "com.fasterxml.jackson.core:jackson-annotations": "2.5.0",
        "com.fasterxml.jackson.core:jackson-core": "2.5.1",
        "com.fasterxml.jackson.core:jackson-databind": "2.5.1",
        "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml": "2.5.1",
        "com.fasterxml.jackson.datatype:jackson-datatype-guava": "2.5.1",
        "com.fasterxml.jackson.datatype:jackson-datatype-jdk7": "2.5.1",
        "com.fasterxml.jackson.datatype:jackson-datatype-joda": "2.5.1",
        "com.fasterxml.jackson.jaxrs:jackson-jaxrs-base": "2.5.1",
        "com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider": "2.5.1",
        "com.fasterxml.jackson.module:jackson-module-afterburner": "2.5.1",
        "com.fasterxml.jackson.module:jackson-module-jaxb-annotations": "2.5.1",
        "com.fasterxml:classmate": "1.0.0",
        "com.google.guava:guava": "18.0",
        "io.dropwizard-bundles:dropwizard-version-bundle": "0.8.1-2-SNAPSHOT",
        "io.dropwizard.metrics:metrics-annotation": "3.1.1",
        "io.dropwizard.metrics:metrics-core": "3.1.1",
        "io.dropwizard.metrics:metrics-healthchecks": "3.1.1",
        "io.dropwizard.metrics:metrics-jersey2": "3.1.1",
        "io.dropwizard.metrics:metrics-jetty9": "3.1.1",
        "io.dropwizard.metrics:metrics-json": "3.1.1",
        "io.dropwizard.metrics:metrics-jvm": "3.1.1",
        "io.dropwizard.metrics:metrics-logback": "3.1.1",
        "io.dropwizard.metrics:metrics-servlets": "3.1.1",
        "io.dropwizard:dropwizard-configuration": "0.8.1",
        "io.dropwizard:dropwizard-core": "0.8.1",
        "io.dropwizard:dropwizard-jackson": "0.8.1",
        "io.dropwizard:dropwizard-jersey": "0.8.1",
        "io.dropwizard:dropwizard-jetty": "0.8.1",
        "io.dropwizard:dropwizard-lifecycle": "0.8.1",
        "io.dropwizard:dropwizard-logging": "0.8.1",
        "io.dropwizard:dropwizard-metrics": "0.8.1",
        "io.dropwizard:dropwizard-servlets": "0.8.1",
        "io.dropwizard:dropwizard-util": "0.8.1",
        "io.dropwizard:dropwizard-validation": "0.8.1",
        "javax.annotation:javax.annotation-api": "1.2",
        "javax.servlet:javax.servlet-api": "3.1.0",
        "javax.validation:validation-api": "1.1.0.Final",
        "javax.ws.rs:javax.ws.rs-api": "2.0.1",
        "joda-time:joda-time": "2.7",
        "net.sourceforge.argparse4j:argparse4j": "0.4.4",
        "org.apache.commons:commons-lang3": "3.3.2",
        "org.eclipse.jetty.toolchain.setuid:jetty-setuid-java": "1.0.2",
        "org.eclipse.jetty:jetty-continuation": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-http": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-io": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-security": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-server": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-servlet": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-servlets": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-util": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-webapp": "9.2.9.v20150224",
        "org.eclipse.jetty:jetty-xml": "9.2.9.v20150224",
        "org.glassfish.hk2.external:aopalliance-repackaged": "2.4.0-b10",
        "org.glassfish.hk2.external:javax.inject": "2.4.0-b10",
        "org.glassfish.hk2:hk2-api": "2.4.0-b10",
        "org.glassfish.hk2:hk2-locator": "2.4.0-b10",
        "org.glassfish.hk2:hk2-utils": "2.4.0-b10",
        "org.glassfish.hk2:osgi-resource-locator": "1.0.1",
        "org.glassfish.jersey.bundles.repackaged:jersey-guava": "2.17",
        "org.glassfish.jersey.containers:jersey-container-servlet": "2.17",
        "org.glassfish.jersey.containers:jersey-container-servlet-core": "2.17",
        "org.glassfish.jersey.core:jersey-client": "2.17",
        "org.glassfish.jersey.core:jersey-common": "2.17",
        "org.glassfish.jersey.core:jersey-server": "2.17",
        "org.glassfish.jersey.ext:jersey-metainf-services": "2.17",
        "org.glassfish.jersey.media:jersey-media-jaxb": "2.17",
        "org.glassfish:javax.el": "3.0.0",
        "org.hibernate:hibernate-validator": "5.1.3.Final",
        "org.javassist:javassist": "3.18.2-GA",
        "org.jboss.logging:jboss-logging": "3.1.3.GA",
        "org.jvnet:tiger-types": "1.4",
        "org.reflections:reflections": "0.9.9",
        "org.slf4j:jcl-over-slf4j": "1.7.10",
        "org.slf4j:jul-to-slf4j": "1.7.10",
        "org.slf4j:log4j-over-slf4j": "1.7.10",
        "org.slf4j:slf4j-api": "1.7.10",
        "org.yaml:snakeyaml": "1.12"
    }
}
```

**Pull request merged**
